-- Calm in-app updates for meaningful activity that users may want to see.
-- These are generated by database triggers so comments, Prayer Circle invites,
-- and report decisions are captured consistently.

create table if not exists public.activity_events (
  id uuid primary key default gen_random_uuid(),
  recipient_user_id uuid not null references public.profiles(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  event_type text not null
    check (
      event_type in (
        'comment_on_prayer',
        'reply_to_comment',
        'prayer_circle_invite',
        'prayer_circle_accepted',
        'report_reviewed'
      )
    ),
  prayer_id uuid references public.prayer_requests(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  report_id uuid references public.reports(id) on delete cascade,
  invite_id uuid references public.prayer_circle_invites(id) on delete cascade,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_events_recipient_created
  on public.activity_events(recipient_user_id, created_at desc);

create index if not exists idx_activity_events_unread
  on public.activity_events(recipient_user_id, created_at desc)
  where read_at is null;

create unique index if not exists idx_activity_events_comment_unique
  on public.activity_events(recipient_user_id, event_type, comment_id)
  where comment_id is not null
    and event_type in ('comment_on_prayer', 'reply_to_comment');

create unique index if not exists idx_activity_events_invite_unique
  on public.activity_events(recipient_user_id, event_type, invite_id)
  where invite_id is not null
    and event_type in ('prayer_circle_invite', 'prayer_circle_accepted');

create unique index if not exists idx_activity_events_report_unique
  on public.activity_events(recipient_user_id, event_type, report_id)
  where report_id is not null
    and event_type = 'report_reviewed';

alter table public.activity_events enable row level security;

drop policy if exists "Users can view own activity events" on public.activity_events;
create policy "Users can view own activity events"
  on public.activity_events for select
  to authenticated
  using (auth.uid() = recipient_user_id);

drop policy if exists "Users can mark own activity events read" on public.activity_events;
create policy "Users can mark own activity events read"
  on public.activity_events for update
  to authenticated
  using (auth.uid() = recipient_user_id)
  with check (auth.uid() = recipient_user_id);

grant select, update (read_at) on public.activity_events to authenticated;

create or replace function public.create_comment_activity_events()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prayer_owner uuid;
  v_parent_author uuid;
begin
  select user_id
  into v_prayer_owner
  from public.prayer_requests
  where id = new.prayer_id;

  if v_prayer_owner is not null and v_prayer_owner <> new.user_id then
    insert into public.activity_events (
      recipient_user_id,
      actor_user_id,
      event_type,
      prayer_id,
      comment_id,
      metadata
    )
    values (
      v_prayer_owner,
      new.user_id,
      'comment_on_prayer',
      new.prayer_id,
      new.id,
      jsonb_build_object('comment_preview', left(new.body, 140))
    )
    on conflict do nothing;
  end if;

  if new.parent_id is not null then
    select user_id
    into v_parent_author
    from public.comments
    where id = new.parent_id;

    if v_parent_author is not null
      and v_parent_author <> new.user_id
      and v_parent_author is distinct from v_prayer_owner then
      insert into public.activity_events (
        recipient_user_id,
        actor_user_id,
        event_type,
        prayer_id,
        comment_id,
        metadata
      )
      values (
        v_parent_author,
        new.user_id,
        'reply_to_comment',
        new.prayer_id,
        new.id,
        jsonb_build_object('comment_preview', left(new.body, 140))
      )
      on conflict do nothing;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists comments_create_activity_events on public.comments;
create trigger comments_create_activity_events
after insert on public.comments
for each row
execute function public.create_comment_activity_events();

create or replace function public.create_prayer_circle_activity_events()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' and new.status = 'pending' then
    insert into public.activity_events (
      recipient_user_id,
      actor_user_id,
      event_type,
      invite_id,
      metadata
    )
    values (
      new.recipient_id,
      new.requester_id,
      'prayer_circle_invite',
      new.id,
      jsonb_build_object('message', coalesce(new.message, ''))
    )
    on conflict do nothing;
  elsif tg_op = 'UPDATE'
    and new.status = 'accepted'
    and old.status is distinct from new.status then
    insert into public.activity_events (
      recipient_user_id,
      actor_user_id,
      event_type,
      invite_id
    )
    values (
      new.requester_id,
      new.recipient_id,
      'prayer_circle_accepted',
      new.id
    )
    on conflict do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists prayer_circle_invites_create_activity_events
  on public.prayer_circle_invites;
create trigger prayer_circle_invites_create_activity_events
after insert or update on public.prayer_circle_invites
for each row
execute function public.create_prayer_circle_activity_events();

create or replace function public.create_report_activity_events()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status in ('resolved', 'dismissed')
    and old.status is distinct from new.status then
    insert into public.activity_events (
      recipient_user_id,
      actor_user_id,
      event_type,
      report_id,
      metadata
    )
    values (
      new.reported_by,
      new.resolved_by,
      'report_reviewed',
      new.id,
      jsonb_build_object('status', new.status)
    )
    on conflict do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists reports_create_activity_events on public.reports;
create trigger reports_create_activity_events
after update on public.reports
for each row
execute function public.create_report_activity_events();

revoke all on function public.create_comment_activity_events() from public;
revoke all on function public.create_prayer_circle_activity_events() from public;
revoke all on function public.create_report_activity_events() from public;
